include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.gr.dart
    - test/**/*.mocks.dart

linter:
  rules:
    depend_on_referenced_packages: false
    prefer_relative_imports: true
    prefer_single_quotes: true